// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aplicacionweb.Data;

#nullable disable

namespace aplicacionweb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("aplicacionweb.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int>("TipoOfertaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoOfertaId");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("aplicacionweb.Models.TipoOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreOferta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoOferta");
                });

            modelBuilder.Entity("aplicacionweb.Models.Oferta", b =>
                {
                    b.HasOne("aplicacionweb.Models.TipoOferta", "TipoOferta")
                        .WithMany("Oferta")
                        .HasForeignKey("TipoOfertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoOferta");
                });

            modelBuilder.Entity("aplicacionweb.Models.TipoOferta", b =>
                {
                    b.Navigation("Oferta");
                });
#pragma warning restore 612, 618
        }
    }
}
